### ISSUE TITLE
gpg: cannot open tty

### ISSUE THREAD

**Issue by jingxuanlim** [jabranham/helm-pass#7]
Hi. I just installed helm-pass and am very excited to get it to work.

Whenever I try to have helm-pass copy the password to the clipboard, an error occurs:

```
password-store--run: gpg: cannot open tty ‘/dev/tty’: No such device or address
```

Looks like a problem when gpg is not run interactively.

What can I do about this?

**Comment by jabranham** [comment]
The easy answer is to just run gpg interactively. 

If you can't do that for whatever reason, though, you could try something along the following lines: http://unix.stackexchange.com/questions/55638/can-emacs-use-gpg-agent-in-a-terminal-at-all/278875#278875

Or this: http://www.thedumbterminal.co.uk/posts/2012/02/running_gpg_from_a_cron_or_application.html

Since this is a problem with gpg and not helm-pass, I'm going to close the issue.
