### ISSUE TITLE
Does password-store-url work at all?

### ISSUE THREAD

**Issue by Ambrevar** [jabranham/helm-pass#9]
Whenever I try to "Browse url of entry", I get the following error:

    if: String does not look like a URL

Looking at the code in `password-store.el`, it seems that `password-store-url` is only getting the first line, that is, the password.  I can't see how this was ever supposed to work.
Is it a mistake in upstream?

Since you've implemented the action, I'm asking here as you might have run it successfully.

**Comment by jabranham** [comment]
No, it's never worked for me. Looking at the documentation, I assumed that entries had to be files like "~/.password-store/http-site.com" or some such. Since mine isn't organized like that, I didn't think much about it not working for me. Just put it in since I figured it'd be useful for others.

But you're right, looking at the code I'm not sure how that's supposed to work.

**Comment by Ambrevar** [comment]
Reported upstream: https://lists.zx2c4.com/pipermail/password-store/2018-February/003210.html.

Nothing more can be done here, so I'm going to close this issue.
